### ISSUE TITLE
0.4.2 crashing on start

### ISSUE THREAD

**Issue by Knodd** [Danielhiversen/home_assistant_tibber_data#19]
0.4.2 is crashing for me

`Error while setting up tibber_data platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tibber_data/sensor.py", line 52, in async_setup_platform
    for (
TypeError: 'NoneType' object is not iterable
 `

the error happens when iterating over "chargers_entity_descritpions". Maybe a typo here but I tested changing to chargers_entity_descriptions and error was still there.
Could it be because I have no chargers? Seems the code will return an empty list if no chargers...

**Comment by Danielhiversen** [comment]
Fixed by https://github.com/Danielhiversen/home_assistant_tibber_data/commit/98b1a97c96a579671a7cf8634dc3e817b1274a41
