### ISSUE TITLE
No sensors are created

### ISSUE THREAD

**Issue by Wiigian** [Danielhiversen/home_assistant_tibber_data#24]
Installed via HACS and restarted Home Assistant.
Existing tibber integration is configured and working.
I can not find any new sensors. Should they appear as a new integration? 

Versions:
- HACS, 1.27.2
- Tibberdata, 0.4.3
- Home Assistant, 2022.9.7

**Comment by kongjudas** [comment]
The entities are from time to time. I't very unstable, so maybe try again in an hour or so.

**Comment by Danielhiversen** [comment]
Errors in the log?

**Comment by SVH-Powel** [comment]
> Errors in the log?

No

But I get this error from the Tibber integration. It works after the second try to log in, it seems. But can this cause a failure in the tibber_data integration if it depends on the Tibber integration?

`2022-10-04 06:49:02.034 ERROR (MainThread) [tibber] Timed out when connecting to Tibber
2022-10-04 06:49:02.038 WARNING (MainThread) [homeassistant.config_entries] Config entry 'xxxxxxxxx xxxxxxxxx' for tibber integration not ready yet; Retrying in background`

**Comment by Danielhiversen** [comment]
It depends on data from the tibber integration, so it will not work without it.

**Comment by SVH-Powel** [comment]
> It depends on data from the tibber integration, so it will not work without it.

So the Tibber integration is retrying and works after some time after startup, but the tibber_data integration is not retrying?

**Comment by Danielhiversen** [comment]
Yeah, that could be the reason

**Comment by Wiigian** [comment]
I updated and restarted again today, and now I can see the sensors. Not sure what was going on.
