### ISSUE TITLE
How to install on HomeAssistant Core?

### ISSUE THREAD

**Issue by mrbardman** [Danielhiversen/home_assistant_tibber_data#32]
I dropped the folder tibber_data into my HA Core custom_components folder, set owner to homeassistant:homeassistant like my two other custom components. I put "tibber_data:" in my configuration.yaml and first restarted HA then rebooted the RPi. 

No integration, devices or entities with tibber_data shows up.

How to install tibber_data on HA Core?

**Comment by Danielhiversen** [comment]
https://community.home-assistant.io/t/install-custom-components/423871
