### ISSUE TITLE
price without tax

### ISSUE THREAD

**Issue by trackd** [Danielhiversen/home_assistant_tibber_data#35]
Hello

Would it be possible to add the spot price witout tax

right now price is from the total  value

**"total": 0.5116,**
"energy": 0.3497,
"tax": 0.1619,

I need the **energy** value in order to calc my solar production sales.

**Comment by AnonymousRetard** [comment]
I would like this as well. Personally I need this information to be able to precisely calculate if it's better to use my own excess energy production or if it's better to delay "jobs" (like running the dishwasher/washing machine/water heater) and run them later at night when energy is cheap and instead sell more of my excess energy production. Sometimes selling energy is worth quite a lot and at other times it can even cost money...

I would need these values for all hours of the day. (energy_price attributes "today" & "tomorrow")
