### ISSUE TITLE
Multiple Accounts?

### ISSUE THREAD

**Issue by theeogflip** [Danielhiversen/home_assistant_tibber_data#71]
Hi,

we have 2 Houses and 2 Tibber Accounts.

at the moment i just can connect one account to home assistant.

is there any solution to put the second account also to home assistant?

<img width="497" alt="grafik" src="https://github.com/Danielhiversen/home_assistant_tibber_data/assets/71273867/392f28d4-65f6-466f-9557-1bb4e539c6fc">

**Comment by Danielhiversen** [comment]
Not supported today
