### ISSUE TITLE
Suggestion: Add "away" as binary_sensor

### ISSUE THREAD

**Issue by bnordli** [Danielhiversen/home_assistant_tibber_data#74]
Is it possible to get the away/vacation status from the Tibber API and expose it as a binary_sensor?

(And if possible, the next planned change (leaving/returning) as an attribute.)

**Comment by Danielhiversen** [comment]
Not exposed by the Tibber API.
Send a feature request to Tibber.

**Comment by bnordli** [comment]
Thanks for the response. I will check with Tibber :-)
