### ISSUE TITLE
Atribute doesnt update. 

### ISSUE THREAD

**Issue by FSHelgeland** [Danielhiversen/home_assistant_tibber_data#75]
I am having trouble with the attribute for price level not updating. Sometimes it does but in long periods it keeps stuck in VERY_EXPENSIVE and when I run my heating and hot water based on these atributes, the the WAF is not very high! As for now it looks like this ```

sensor.electricity_price_hjemmeElectricity price Hjemme | 0.13 | state_class: measurement app_nickname: Hjemme grid_company: Linea AS estimated_annual_consumption: 29964 price_level: VERY_EXPENSIVE max_price: 0.173 avg_price: 0.137 min_price: 0.095 off_peak_1: 0.119 peak: 0.158 off_peak_2: 0.114 unit_of_measurement: NOK/kWh icon: mdi:currency-usd friendly_name: Electricity price Hjemme
-- | -- | --

[sensor.electricity_price_hjemme](http://10.0.0.47:8123/developer-tools/state#)
Electricity price Hjemme
0.13	state_class: measurement
app_nickname: Hjemme
grid_company: Linea AS
estimated_annual_consumption: 29964
price_level: VERY_EXPENSIVE
max_price: 0.173
avg_price: 0.137
min_price: 0.095
off_peak_1: 0.119
peak: 0.158
off_peak_2: 0.114
unit_of_measurement: NOK/kWh
icon: mdi:currency-usd
friendly_name: Electricity price Hjemme```

So even if the price now is lower than average, it still reports VERY_EXPENSIVE. It this a bug? Or can I do something to avoid this?

Freddy

**Comment by FSHelgeland** [comment]
This should probably been in the Tibber page and not Tibber data, but I hope Daniel can have a look at it anyway. Now at this moment the price dropped to 0.126 and the average is 0.137. The atribute did update but it states EXPENSIVE, according to Tibber it should have been NORMAL as NORMAL is from 90-115%.

**Comment by FSHelgeland** [comment]
But as the price info is correct I made my own sensor based on them, so for now I am good.

**Comment by Danielhiversen** [comment]
Not related to this repo.

Please verify if you also get VERY_EXPENSIVE from the tibber api https://developer.tibber.com/explorer

I would not recommend using that for controlling any devices.
