### ISSUE TITLE
Hourly Cost

### ISSUE THREAD

**Issue by mlo-Tek** [Danielhiversen/home_assistant_tibber_data#86]
Hello,

it's not an issue, more a request / question? Is it possible to integrate a hourly cost sensor which resets every hour? I simply could not figure it out how to solve this otherwise ( e.g. with template code etc.)

As i can see the hourly price in the tibber app i thought this would be the easiest way to implement it.

Thanks

**Comment by Danielhiversen** [comment]
I have no plan to add that
