### ISSUE TITLE
Additional calculated Sensor

### ISSUE THREAD

**Issue by Styx85** [Danielhiversen/home_assistant_tibber_data#87]
Hi,
would it be possible to integrate an additional sensor leige in the the [ EPEX Spot data integration](https://github.com/mampfes/ha_epex_spot).

Especially interesting is the Quantile-Sensor. As it is possible to create automations like "start washing machine when quantile is below 5 %"

>7. Quantile Sensor
>The sensor value reports the quantile between the lowest market price and the highest market price during the day in the range between 0 & 1.
> 
> Examples:
>    The sensor reports 0 if the current market price is the lowest during the day.
>    The sensor reports 1 if the current market price is the highest during the day.
>    If the sensor reports e.g., 0.25, then the current market price is 25% of the range between the lowest and the highest market price.
>

**Comment by Danielhiversen** [comment]
No plan to do so
